### PR TITLE
Month 9/step 2

### PR DESCRIPTION
**Pull request by IlyaKZN**

### CODE REVIEW

**Comment by irinamozes** [comment]
Здравствуйте, Илья.

Проект не заработал с ошибками Typescript в консоли инструментов разработчика (см. снимок). Ошибка с NavLink была и у других студентов, кому-то помогло оборачивание NavLink в элемеент-фрагмент.
Снимок экрана в 2022-04-13 18-22-46
Над другими ошибками надо подумать, если совсем не получится исправить, наверное, можно игнорировать тайпскриптом (// @ts-ignore).
У меня операционная система Linux, ubuntu 20.04, node v16.13.2, npm v8.1.2.

Текущая итерация засчитываться не будет, без потери количества итераций.

Скопировала все сообщения об ошибках при компиляции:

```
Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload (vendors~main.chunk.js:45302:324845)
```
index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/components/button-header/button-header.tsx
TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/components/button-header/button-header.tsx(42,6):
This JSX tag's 'children' prop expects a single child of type 'ReactNode', but multiple children were provided.  TS2746
```

    40 | 
    41 |   return (
  > 42 |     <NavLink 
       |      ^
    43 |       exact
    44 |       to={state.link} 
    45 |       ref={linkRef}
```
console.<computed> @ index.js:1
index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/components/protected-route/protected-route.tsx
TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/components/protected-route/protected-route.tsx(63,7):
No overload matches this call.
  Overload 1 of 2, '(props: (RouteProps<string, { [x: string]: string | undefined; }> & OmitNative<{}, keyof RouteProps<string, { [x: string]: string | undefined; }>>) | Readonly<...>): Route<...>', gave the following error.
    Type 'ReactNode' is not assignable to type 'ReactNode | ((props: RouteChildrenProps<{ [x: string]: string | undefined; }, unknown>) => ReactNode)'.
      Type '{}' is not assignable to type 'ReactNode | ((props: RouteChildrenProps<{ [x: string]: string | undefined; }, unknown>) => ReactNode)'.
  Overload 2 of 2, '(props: RouteProps<string, { [x: string]: string | undefined; }> & OmitNative<{}, keyof RouteProps<string, { [x: string]: string | undefined; }>>, context: any): Route<...>', gave the following error.
    Type 'ReactNode' is not assignable to type 'ReactNode | ((props: RouteChildrenProps<{ [x: string]: string | undefined; }, unknown>) => ReactNode)'.  TS2769
```

    61 |   return (
    62 |     <Route {...rest}>
  > 63 |       {children}
       |       ^
    64 |     </Route>
    65 |   ) 
    66 | }

```
console.<computed> @ index.js:1
index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts
TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts(262,14):
Type '(email: string) => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk<void>'.
  Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'.
    Types of parameters 'dispatch' and 'dispatch' are incompatible.
      Type 'ThunkDispatch<Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'.  TS2322

```
    260 | };
    261 | 
  > 262 | export const requestPasswordChange: AppThunk = (email: string) => {
        |              ^
    263 |   return function (dispatch: AppDispatch) {
    264 |     dispatch({
    265 |       type: REQUEST_PASSWORD_CHANGE_ACTIVE, 

```
console.<computed> @ index.js:1
index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts
TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts(285,14):
Type '(password: string, code: string) => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk<void>'.
  Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'.
    Types of parameters 'dispatch' and 'dispatch' are incompatible.
      Type 'ThunkDispatch<Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'.  TS2322

```
    283 | };
    284 | 
  > 285 | export const resetPassword: AppThunk = (password: string, code: string) => {
        |              ^
    286 |   return function (dispatch: AppDispatch) {
    287 |     dispatch({
    288 |       type: RESET_PASSWORD_REQUEST,
```
console.<computed> @ index.js:1
index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts
TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts(308,14):
Type '(name: string, email: string, password: string) => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk<void>'.
  Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'.
    Types of parameters 'dispatch' and 'dispatch' are incompatible.
      Type 'ThunkDispatch<Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'.  TS2322

```
    306 | };
    307 | 
  > 308 | export const changeUserData: AppThunk = (
        |              ^
    309 |   name: string,
    310 |   email: string,
    311 |   password: string

```
console.<computed> @ index.js:1
index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts
TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts(333,14):
Type '() => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk<void>'.
  Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'.
    Types of parameters 'dispatch' and 'dispatch' are incompatible.
      Type 'ThunkDispatch<Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'.  TS2322

```
    331 | };
    332 | 
  > 333 | export const getUser: AppThunk = () => {
        |              ^
    334 |   return function (dispatch: AppDispatch) {
    335 |     dispatch({
    336 |       type: GET_USER_REQUEST,  
```

console.<computed> @ index.js:1
index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/index.ts
TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/index.ts(133,14):
Type '() => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk<void>'.
  Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'.
    Types of parameters 'dispatch' and 'dispatch' are incompatible.
      Type 'ThunkDispatch<Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'.
        Type 'Action<any>' is not assignable to type 'EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; orderReducer: TInitialStateOrder; dndReducer: TInitialStateDnd; userReducer: TInitialState; feedOrdersReducer: TFeedInitialState; userOrdersReducer: TOrdersInitialState; }'.
          Type 'Action<any>' is missing the following properties from type '{ viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; orderReducer: TInitialStateOrder; dndReducer: TInitialStateDnd; userReducer: TInitialState; feedOrdersReducer: TFeedInitialState; userOrdersReducer: TOrdersInitialState; }': viewedIngredientReducer, ingredientsReducer, orderReducer, dndReducer, and 3 more.  TS2322

```
    131 | 
    132 | 
  > 133 | export const getIngredients: AppThunk = () => {
        |              ^
    134 |   return function (dispatch: AppDispatch) {
    135 |     dispatch({
    136 |       type: GET_INGREDIENTS_REQUEST,

```
console.<computed> @ index.js:1
index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/index.ts
TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/index.ts(154,14):
Type '(idList: string[]) => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk<void>'.
  Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'.
    Types of parameters 'dispatch' and 'dispatch' are incompatible.
      Type 'ThunkDispatch<Action<any>, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'.  TS2322

```
    152 | }
    153 | 
  > 154 | export const getOrder: AppThunk = (idList: string[]) => {
        |              ^
    155 |   return function (dispatch: AppDispatch) {
    156 |     dispatch({
    157 |       type: GET_ORDER_REQUEST,
```

console.<computed> @ index.js:1

**Comment by IlyaKZN** [comment]
> Здравствуйте, Илья.
> 
> Проект не заработал с ошибками Typescript в консоли инструментов разработчика (см. снимок). Ошибка с NavLink была и у других студентов, кому-то помогло оборачивание NavLink в элемеент-фрагмент. Снимок экрана в 2022-04-13 18-22-46 Над другими ошибками надо подумать, если совсем не получится исправить, наверное, можно игнорировать тайпскриптом (// @ts-ignore). У меня операционная система Linux, ubuntu 20.04, node v16.13.2, npm v8.1.2.
> 
> Текущая итерация засчитываться не будет, без потери количества итераций.
> 
> Скопировала все сообщения об ошибках при компиляции:
> 
> ```
> Uncaught ReferenceError: process is not defined
>     at Object.4043 (<anonymous>:2:13168)
>     at r (<anonymous>:2:306599)
>     at Object.8048 (<anonymous>:2:9496)
>     at r (<anonymous>:2:306599)
>     at Object.8641 (<anonymous>:2:1379)
>     at r (<anonymous>:2:306599)
>     at <anonymous>:2:315627
>     at <anonymous>:2:324225
>     at <anonymous>:2:324229
>     at HTMLIFrameElement.e.onload (vendors~main.chunk.js:45302:324845)
> ```
> 
> index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/components/button-header/button-header.tsx TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/components/button-header/button-header.tsx(42,6): This JSX tag's 'children' prop expects a single child of type 'ReactNode', but multiple children were provided. TS2746
> 
> ```
> 
>     40 | 
>     41 |   return (
>   > 42 |     <NavLink 
>        |      ^
>     43 |       exact
>     44 |       to={state.link} 
>     45 |       ref={linkRef}
> ```
> 
> console. @ index.js:1 index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/components/protected-route/protected-route.tsx TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/components/protected-route/protected-route.tsx(63,7): No overload matches this call. Overload 1 of 2, '(props: (RouteProps<string, { [x: string]: string | undefined; }> & OmitNative<{}, keyof RouteProps<string, { [x: string]: string | undefined; }>>) | Readonly<...>): Route<...>', gave the following error. Type 'ReactNode' is not assignable to type 'ReactNode | ((props: RouteChildrenProps<{ [x: string]: string | undefined; }, unknown>) => ReactNode)'. Type '{}' is not assignable to type 'ReactNode | ((props: RouteChildrenProps<{ [x: string]: string | undefined; }, unknown>) => ReactNode)'. Overload 2 of 2, '(props: RouteProps<string, { [x: string]: string | undefined; }> & OmitNative<{}, keyof RouteProps<string, { [x: string]: string | undefined; }>>, context: any): Route<...>', gave the following error. Type 'ReactNode' is not assignable to type 'ReactNode | ((props: RouteChildrenProps<{ [x: string]: string | undefined; }, unknown>) => ReactNode)'. TS2769
> 
> ```
> 
>     61 |   return (
>     62 |     <Route {...rest}>
>   > 63 |       {children}
>        |       ^
>     64 |     </Route>
>     65 |   ) 
>     66 | }
> ```
> 
> console. @ index.js:1 index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts(262,14): Type '(email: string) => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk'. Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'. Types of parameters 'dispatch' and 'dispatch' are incompatible. Type 'ThunkDispatch<Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'. TS2322
> 
> ```
>     260 | };
>     261 | 
>   > 262 | export const requestPasswordChange: AppThunk = (email: string) => {
>         |              ^
>     263 |   return function (dispatch: AppDispatch) {
>     264 |     dispatch({
>     265 |       type: REQUEST_PASSWORD_CHANGE_ACTIVE, 
> ```
> 
> console. @ index.js:1 index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts(285,14): Type '(password: string, code: string) => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk'. Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'. Types of parameters 'dispatch' and 'dispatch' are incompatible. Type 'ThunkDispatch<Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'. TS2322
> 
> ```
>     283 | };
>     284 | 
>   > 285 | export const resetPassword: AppThunk = (password: string, code: string) => {
>         |              ^
>     286 |   return function (dispatch: AppDispatch) {
>     287 |     dispatch({
>     288 |       type: RESET_PASSWORD_REQUEST,
> ```
> 
> console. @ index.js:1 index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts(308,14): Type '(name: string, email: string, password: string) => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk'. Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'. Types of parameters 'dispatch' and 'dispatch' are incompatible. Type 'ThunkDispatch<Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'. TS2322
> 
> ```
>     306 | };
>     307 | 
>   > 308 | export const changeUserData: AppThunk = (
>         |              ^
>     309 |   name: string,
>     310 |   email: string,
>     311 |   password: string
> ```
> 
> console. @ index.js:1 index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/authorization.ts(333,14): Type '() => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk'. Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'. Types of parameters 'dispatch' and 'dispatch' are incompatible. Type 'ThunkDispatch<Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'. TS2322
> 
> ```
>     331 | };
>     332 | 
>   > 333 | export const getUser: AppThunk = () => {
>         |              ^
>     334 |   return function (dispatch: AppDispatch) {
>     335 |     dispatch({
>     336 |       type: GET_USER_REQUEST,  
> ```
> 
> console. @ index.js:1 index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/index.ts TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/index.ts(133,14): Type '() => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk'. Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'. Types of parameters 'dispatch' and 'dispatch' are incompatible. Type 'ThunkDispatch<Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'. Type 'Action' is not assignable to type 'EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; orderReducer: TInitialStateOrder; dndReducer: TInitialStateDnd; userReducer: TInitialState; feedOrdersReducer: TFeedInitialState; userOrdersReducer: TOrdersInitialState; }'. Type 'Action' is missing the following properties from type '{ viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; orderReducer: TInitialStateOrder; dndReducer: TInitialStateDnd; userReducer: TInitialState; feedOrdersReducer: TFeedInitialState; userOrdersReducer: TOrdersInitialState; }': viewedIngredientReducer, ingredientsReducer, orderReducer, dndReducer, and 3 more. TS2322
> 
> ```
>     131 | 
>     132 | 
>   > 133 | export const getIngredients: AppThunk = () => {
>         |              ^
>     134 |   return function (dispatch: AppDispatch) {
>     135 |     dispatch({
>     136 |       type: GET_INGREDIENTS_REQUEST,
> ```
> 
> console. @ index.js:1 index.js:1 /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/index.ts TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_1_iter/src/services/actions/index.ts(154,14): Type '(idList: string[]) => (dispatch: AppDispatch) => void' is not assignable to type 'AppThunk'. Type '(dispatch: AppDispatch) => void' is not assignable to type 'ThunkAction<void, Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>'. Types of parameters 'dispatch' and 'dispatch' are incompatible. Type 'ThunkDispatch<Action, EmptyObject & { viewedIngredientReducer: TInitialStateViewedIngredient; ingredientsReducer: TInitialState; ... 4 more ...; userOrdersReducer: TOrdersInitialState; }, TAppActions>' is not assignable to type 'AppDispatch'. TS2322
> 
> ```
>     152 | }
>     153 | 
>   > 154 | export const getOrder: AppThunk = (idList: string[]) => {
>         |              ^
>     155 |   return function (dispatch: AppDispatch) {
>     156 |     dispatch({
>     157 |       type: GET_ORDER_REQUEST,
> ```
> 
> console. @ index.js:1

**Comment by IlyaKZN** [comment]
Здравствуйте, по какой-то причине не вижу у себя этих ошибок, не подскажите в чём может быть причина?

**Comment by irinamozes** [comment]
Почему Вы не видете этих ошибок, точно не могу сказать. Можно предположить, что другая операционная система, другая версия npm и Typescript. Но, мне кажется всё равно надо бы вникнуть в смысл сообщений, он, мне кажется, есть...

**Comment by irinamozes** [comment]
Проект очень хороший.

Создаются два сокет-соединения - для авторизованного и неавторизованного пользователей.
Создан один сокет-миддлвар, параметрами  которого является объект экшенов, поэтому миддлвар может быть применён для обоих соединений, что совершенно правильно.
Нет дублирования кода при создании ленты и истории заказов.
Правильно показывается модальное окно с различным содержимым и детальные страницы ингредиента и карточек заказов.
Спустя 20 минут после входа в ЛК, когда аксесс-токен стал просроченным, при сохранении измененённых данных профиля обновились токены, как и должно быть, и неудавшийся до этого запрос на обновление данных профиля
повторился (см. снимок). Обновлённые данные сохранились.
Снимок экрана в 2022-04-14 11-43-35

Что нужно исправить.

1. Для бОльшей надёжности сокет-соединения нужно типизировать экшены сокета для авторизованного и неавторизованного пользователей не просто как "string". То есть создать тип` type TwsActions` в файле socketMiddleware.ts примерно такого вида (обозначения тут не Ваши, но напишите выражение в соответствии со своим кодом и отладьте):
```
type TwsActions = {
    wsInit: typeof WS_CONNECTION_START | typeof WS_PROFILE_CONNECTION_START,
    onOpen: typeof WS_CONNECTION_SUCCESS | typeof WS_PROFILE_CONNECTION_SUCCESS,
    onClose: typeof WS_CONNECTION_CLOSED | typeof WS_PROFILE_CONNECTION_CLOSED,
    onError: typeof WS_CONNECTION_ERROR | typeof WS_PROFILE_CONNECTION_ERROR,
    onMessage: typeof WS_GET_MESSAGE | typeof WS_PROFILE_GET_MESSAGE
}
```

Что можно лучше.

1. При компиляции появлялась одна ошибка TypeScript:
Failed to compile.

/home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_2_iter/src/components/protected-route/protected-route.tsx
TypeScript error in /home/user/yandex_review/react_developer/5_new7/16_Илья_Пичугин/react-burger-month-9-step-2_2_iter/src/components/protected-route/protected-route.tsx(64,22):
No overload matches this call.
  Overload 1 of 2, '(props: (RouteProps<string, { [x: string]: string | undefined; }> & OmitNative<{}, keyof RouteProps<string, { [x: string]: string | undefined; }>>) | Readonly<...>): Route<...>', gave the following error.
    Type '() => React.ReactNode' is not assignable to type '(props: RouteComponentProps<{ [x: string]: string | undefined; }, StaticContext, unknown>) => ReactNode'.
      Type 'React.ReactNode' is not assignable to type 'import("/home/user/yandex_review/react_developer/5_new7/16_\u0418\u043B\u044C\u044F_\u041F\u0438\u0447\u0443\u0433\u0438\u043D/react-burger-month-9-step-2_2_iter/node_modules/@types/react-router/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
  Overload 2 of 2, '(props: RouteProps<string, { [x: string]: string | undefined; }> & OmitNative<{}, keyof RouteProps<string, { [x: string]: string | undefined; }>>, context: any): Route<...>', gave the following error.
    Type '() => React.ReactNode' is not assignable to type '(props: RouteComponentProps<{ [x: string]: string | undefined; }, StaticContext, unknown>) => ReactNode'.  TS2769
```
    62 |
    63 |   return (
  > 64 |     <Route {...rest} render={() => {
       |                      ^
    65 |       return children
    66 |     }} />
    67 |   )

```

После задания игнорирования ts для ошибочной строки:

```
return (
    // @ts-ignore
    <Route {...rest} render={() => {
      return children
    }} />
)
```
проект заработал, но лучше разобраться в этой ошибке.

2. Я бы рекомендовала для лучшей согласованности типов типизировать метод dispatch и все асинхронные экшены точно по той схеме, как написано в лекции "Вспомогательные типы: хранилище, Redux Thunk, хуки". То, есть для типизации метода dispatch использовать тип Dispatch из 'redux', а не ThunkDispatch из "redux-thunk". Все асинхронные экшены типизировать с помощью AppThunk.

**Comment by irinamozes** [comment]
Проект очень хороший!

Надёжный.

Задание принимается.

Желаю дальнейших успехов в учёбе и удачи!

**Pull request merged**
